# Generated by Django 5.0.6 on 2024-05-17 18:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_alter_groupitem_options_alter_chapter_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chapter",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="subchapter",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
