# Generated by Django 5.0.6 on 2024-05-17 21:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0004_alter_chapter_url_alter_groupitem_url_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="groupitem",
            name="book",
            field=models.FileField(upload_to="books/"),
        ),
        migrations.AlterField(
            model_name="groupitem",
            name="photo",
            field=models.ImageField(upload_to="photos/"),
        ),
    ]
