# Generated by Django 5.0.6 on 2024-05-18 00:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0005_alter_groupitem_book_alter_groupitem_photo"),
    ]

    operations = [
        migrations.CreateModel(
            name="Exercise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "sub_chapter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.subchapter"
                    ),
                ),
            ],
            options={
                "verbose_name": "Упражнение",
                "verbose_name_plural": "Упражнения",
            },
        ),
        migrations.CreateModel(
            name="Exercise1",
            fields=[
                (
                    "exercise_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="api.exercise",
                    ),
                ),
                ("answer", models.CharField(max_length=255)),
            ],
            bases=("api.exercise",),
        ),
    ]
